-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activation_code_candidates
(
    id integer NOT NULL,
    candidate_user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_code_employers
(
    id integer NOT NULL,
    employers_user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_codes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    activation_code character varying(20) NOT NULL,
    is_confirmed boolean NOT NULL,
    confirm_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_cv_experience
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    work_place_name character varying(50) NOT NULL,
    start_date date NOT NULL,
    quit_date date,
    job_positions_id integer NOT NULL,
    candidates_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_cv_language
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    language_level integer NOT NULL,
    candidates_id integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_cv_school
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    school_department character varying(50) NOT NULL,
    school_start_date date,
    school_graduation_date date,
    candidates_id integer NOT NULL,
    school_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_cv_technology
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    used_technology character varying(50) NOT NULL,
    candidates_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    candidates_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    identity_number character varying(11) NOT NULL,
    birth_date date NOT NULL,
    candidate_photo character varying(250),
    PRIMARY KEY (candidates_id)
);

CREATE TABLE public.city
(
    city_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying NOT NULL,
    PRIMARY KEY (city_id)
);

CREATE TABLE public.cv_cover_letter
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    comment character varying(500),
    candidates_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    employees_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    approval_of_employee character varying(50),
    PRIMARY KEY (employees_id)
);

CREATE TABLE public.employers
(
    employers_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_address character varying(50) NOT NULL,
    phone_number character varying(20) NOT NULL,
    is_activated boolean NOT NULL,
    PRIMARY KEY (employers_id)
);

CREATE TABLE public.employers_activation_by_employees
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    employee_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    confirm_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_advertisement
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 5 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_description character varying(50) NOT NULL,
    number_of_position integer NOT NULL,
    application_date date NOT NULL,
    created_at date NOT NULL,
    enable boolean NOT NULL,
    city_id integer NOT NULL,
    employers_id integer NOT NULL,
    job_positions_id integer NOT NULL,
    min_salary integer,
    max_salary integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    job_positions_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(50) NOT NULL,
    PRIMARY KEY (job_positions_id)
);

CREATE TABLE public.links
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    github_link character varying NOT NULL,
    linkedin_link character varying NOT NULL,
    is_active boolean,
    is_deleted boolean,
    candidates_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.school_types
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type_name character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.schools
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(200) NOT NULL,
    school_type integer NOT NULL,
    school_website character varying(150),
    school_logo character varying(200),
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activation_code_candidates
    ADD FOREIGN KEY (candidate_user_id)
    REFERENCES public.candidates (candidates_id)
    NOT VALID;


ALTER TABLE public.activation_code_candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.activation_code_employers
    ADD FOREIGN KEY (employers_user_id)
    REFERENCES public.employers (employers_id)
    NOT VALID;


ALTER TABLE public.activation_code_employers
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.candidate_cv_experience
    ADD FOREIGN KEY (id)
    REFERENCES public.job_positions (job_positions_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (employees_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employees_id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_employees
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (employers_id)
    NOT VALID;

END;
